### ISSUE TITLE
DLL not found

### ISSUE THREAD

**Issue by bostrot** [lamiastella/FaceTracking#1]
Hi, I have an error while compiling this. It says that it can't Access the DLL because of it's Format. Is this example compatible with the newest SDK Version? OR do you know how I can fix this?
Would be nice if you could help me.

**Comment by monajalal** [comment]
I'd suggest you try on intel developer forum in Intel RealSense 3d SDK and write the exact error you receive as well as the link to this repo. I haven't used it in like 10 months and I don't have access to the device anymore. They would also require you to show screenshots of the code, running environment as well as more details on the system specifics (uname -a). Hope this helps.

**Comment by monajalal** [comment]
Also you can write the error here, just in case anyone knows the answer they will answer here as well. Other suggestion is asking over Stackoverflow. I used to ask in all three!

**Comment by bostrot** [comment]
Thanks for your help. I will try it.
